Repository playdata-aichief-ai/aichief-springboot-backend, pull requests merged in 2022-11, with the labels that each got.

#28 Fix CORS config
  src/main/java/kr/pe/aichief/config/WebConfig.java
Labels: fix

#31 청구서 Update 기능 추가
  src/main/java/kr/pe/aichief/controller/ClaimController.java
  src/main/java/kr/pe/aichief/model/service/AccidentService.java
  src/main/java/kr/pe/aichief/model/service/ClaimService.java
Labels: feature

#32 청구 취소 기능 추가 및 청구 수정 기능 일부 수정
  src/main/java/kr/pe/aichief/controller/ClaimController.java
  src/main/java/kr/pe/aichief/exceptions/InvalidInputException.java
  src/main/java/kr/pe/aichief/exceptions/MyExceptionHandler.java
  src/main/java/kr/pe/aichief/model/dto/ClaimPostRequest.java
  src/main/java/kr/pe/aichief/model/dto/ClaimPutRequest.java
  src/main/java/kr/pe/aichief/model/entity/Account.java
  src/main/java/kr/pe/aichief/model/entity/Identification.java
  src/main/java/kr/pe/aichief/model/repository/AccountRepository.java
  src/main/java/kr/pe/aichief/model/repository/AnotherSubscribeRepository.java
  src/main/java/kr/pe/aichief/model/repository/AssignRepository.java
  src/main/java/kr/pe/aichief/model/repository/BeneficiaryRepository.java
  src/main/java/kr/pe/aichief/model/repository/ClaimRepository.java
  src/main/java/kr/pe/aichief/model/repository/IdentificationRepository.java
  src/main/java/kr/pe/aichief/model/repository/InsuredRepository.java
  src/main/java/kr/pe/aichief/model/service/AccidentService.java
  src/main/java/kr/pe/aichief/model/service/ClaimService.java
  src/test/java/kr/pe/aichief/model/service/ClaimServiceTest.java
Labels: feature, refactoring

#34 CORS 설정 추가
  src/main/java/kr/pe/aichief/config/WebConfig.java
Labels: fix

#36 CORS 설정 변경
  src/main/java/kr/pe/aichief/config/WebConfig.java
Labels: fix
